name: ARO Public Deployment
on: [workflow_dispatch]
env:
  LOCATION: australiaeast

jobs: 
  aro_networking:
    runs-on: ubuntu-latest
    outputs:
      vnetName: ${{ steps.network.outputs.vnetName }}
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ARO networking
      id: network
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCEGROUP }}
        template: ./modules/aro_public_network.bicep
        parameters: >
          ./action_params/aro_public_networking.parameters.json
          location="${{ env.LOCATION }}"
        deploymentName: aro-public-networking-github-actions

  deploy_aro: 
    needs: aro_networking
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: aro_cluster
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCEGROUP }}
        template: ./modules/aro_cluster.bicep
        parameters: >
          ./action_params/aro_public.parameters.json 
          pullSecret="${{ secrets.PULL_SECRET }}"
          location="${{ env.LOCATION }}"
          aadClientId="${{ secrets.AAD_CLIENT_ID }}"
          aadClientSecret="${{ secrets.AAD_CLIENT_SECRET }}"
          aadObjectId="${{ secrets.AAD_OBJECT_ID }}"
          rpObjectId="${{ secrets.ARO_RP_OB_ID }}"
          vnetName="${{ needs.aro_networking.outputs.vnetName }}"
          addSpRoleAssignment='no'
        deploymentName: aro-public-github-actions