name: ARO Public Deployment
on: [workflow_dispatch]
env:
  LOCATION: australiaeast
  ARO_VNET: aro-vnet
  CLUSTER_NAME: 'aro-cluster'
  RESOURCEGROUP: 'aro-cluster-rg'

jobs: 
  aro_networking:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ARO networking
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RESOURCEGROUP }}
        template: ./modules/aro_public_network.bicep
        parameters: >
          ./action_params/aro_public_networking.parameters.json
          location="${{ env.LOCATION }}"
          spokeVnetName="${{ env.ARO_VNET }}"
        deploymentName: aro-public-networking-github-actions

  deploy_aro: 
    needs: aro_networking
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: aro_cluster
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RESOURCEGROUP }}
        template: ./modules/aro_cluster.bicep
        parameters: >
          ./action_params/aro_public.parameters.json 
          pullSecret="${{ secrets.PULL_SECRET }}"
          clusterName="${{ env.CLUSTER_NAME }}"
          location="${{ env.LOCATION }}"
          aadClientId="${{ secrets.AAD_CLIENT_ID }}"
          aadClientSecret="${{ secrets.AAD_CLIENT_SECRET }}"
          aadObjectId="${{ secrets.AAD_OBJECT_ID }}"
          rpObjectId="${{ secrets.ARO_RP_OB_ID }}"
          spokeVnetName="${{ env.ARO_VNET }}"
          addSpRoleAssignment='no'
        deploymentName: aro-public-github-actions